// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.co.hostfamilydata.domain;

import org.springframework.beans.factory.annotation.Configurable;
import uk.co.hostfamilydata.domain.HostFamily;

privileged aspect HostFamily_Roo_Configurable {
    
    declare @type: HostFamily: @Configurable;
    
}
